config/routes.rb
Musica::Application.routes.draw do

  resources :mp3s

  resources :mp3s do
    resources :ratings
  end

  resources :playlist

  root :to => "home#index"
  put "/playlist" => "playlist#create"


end

app/models/mp3.rb
class Mp3 < ActiveRecord::Base

  # associations
  has_many :ratings

  # validations
  validates_presence_of :url
  validates_presence_of :title
  validates_presence_of :artist_name
  validates_presence_of :length

  def average_rating
    self.ratings.map(&:value).inject(0.0) { |sum,el| sum + el } / self.ratings.map(&:value).size
  end

end

app/models/rating.rb
class Rating < ActiveRecord::Base

  # associations
  belongs_to :mp3

  # validations
  validates_presence_of :user
  validates_presence_of :value



end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

end

app/controllers/mp3s_controller.rb
class Mp3sController < ApplicationController
  # GET /mp3s
  # GET /mp3s.xml
  def index
    @mp3s = Mp3.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @mp3s }
    end
  end

  # GET /mp3s/1
  # GET /mp3s/1.xml
  def show
    @mp3 = Mp3.find(params[:id])
    @average_rating = @mp3.average_rating
    @average_rating = 'n/a'  if @average_rating == 'NaN'

    respond_to do |format|
      format.html # show.html.erb
      format.xml  { render :xml => @mp3 }
    end
  end

  # GET /mp3s/new
  # GET /mp3s/new.xml
  def new
    @mp3 = Mp3.new

    respond_to do |format|
      format.html # new.html.erb
      format.xml  { render :xml => @mp3 }
    end
  end

  # GET /mp3s/1/edit
  def edit
    @mp3 = Mp3.find(params[:id])
  end

  # POST /mp3s
  # POST /mp3s.xml
  def create
    @mp3 = Mp3.new(params[:mp3])

    respond_to do |format|
      if @mp3.save
        format.html { redirect_to(@mp3, :notice => 'Mp3 was successfully created.') }
        format.xml  { render :xml => @mp3, :status => :created, :location => @mp3 }
      else
        format.html { render :action => "new" }
        format.xml  { render :xml => @mp3.errors, :status => :unprocessable_entity }
      end
    end
  end

  # PUT /mp3s/1
  # PUT /mp3s/1.xml
  def update
    @mp3 = Mp3.find(params[:id])

    respond_to do |format|
      if @mp3.update_attributes(params[:mp3])
        format.html { redirect_to(@mp3, :notice => 'Mp3 was successfully updated.') }
        format.xml  { head :ok }
      else
        format.html { render :action => "edit" }
        format.xml  { render :xml => @mp3.errors, :status => :unprocessable_entity }
      end
    end
  end

  # DELETE /mp3s/1
  # DELETE /mp3s/1.xml
  def destroy
    @mp3 = Mp3.find(params[:id])
    @mp3.destroy

    respond_to do |format|
      format.html { redirect_to(mp3s_url) }
      format.xml  { head :ok }
    end
  end

  def playlist
    @mp3s = Mp3.all
  end



end

app/controllers/playlist_controller.rb
class PlaylistController < ApplicationController

  def index
    @mp3s = Mp3.all
  end

  def new
     @artists = Mp3.all.map(&:artist_name).uniq.sort
     @ratings = %w{1 2 3 4 5}
  end


  def create
    @mp3s = [];
    rating = params[:rating][:value]
    artist = params[:artist][:name]

    Mp3.joins(:ratings).where( :mp3s => { :artist_name => artist } ).each { |i| @mp3s << i if i.average_rating >= rating.to_i }
  end


end

app/controllers/ratings_controller.rb
class RatingsController < ApplicationController
  
  def create
      @mp3 = Mp3.find(params[:mp3_id])
      @rating = @mp3.ratings.create(params[:rating])
      redirect_to mp3_path(@mp3)
  end
  
  
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/mp3s_helper.rb
module Mp3sHelper
end

app/helpers/ratings_helper.rb
module RatingsHelper
end

app/views/home/index.html.erb
<h1>Welcome to my MP3 library!</h1> <%= link_to "View My List", mp3s_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Musica</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/mp3s/_form.html.erb
<%= form_for(@mp3) do |f| %>
  <% if @mp3.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@mp3.errors.count, "error") %> prohibited this mp3 from being saved:</h2>

      <ul>
      <% @mp3.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :url %><br />
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :artist_name %><br />
    <%= f.text_field :artist_name %>
  </div>
  <div class="field">
    <%= f.label :length %><br />
    <%= f.text_field :length %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/mp3s/edit.html.erb
<h1>Editing mp3</h1>

<%= render 'form' %>

<%= link_to 'Show', @mp3 %> |
<%= link_to 'Back', mp3s_path %>

app/views/mp3s/index.html.erb
<h2>My Library of MP3s</h2>

<table border="1">
  <tr>
    <th>Url</th>
    <th>Title</th>
    <th>Artist name</th>
    <th>Length</th>
    <th>Average<br>Rating</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @mp3s.each do |mp3| %>
  <tr>
    <td><%= mp3.url %></td>
    <td><%= mp3.title %></td>
    <td><%= mp3.artist_name %></td>
    <td><%= mp3.length %></td>
    <td><%= sprintf( "%0.02f", mp3.average_rating )%></td>
    <td><%= link_to 'Show', mp3 %></td>
    <td><%= link_to 'Edit', edit_mp3_path(mp3) %></td>
    <td><%= link_to 'Destroy', mp3, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'Add Mp3', new_mp3_path %>
<%= link_to 'Playlist', new_playlist_path %>

app/views/mp3s/new.html.erb
<h1>New mp3</h1>

<%= render 'form' %>

<%= link_to 'Back', mp3s_path %>

app/views/mp3s/playlist.html.erb
<b>Current Playlist</b>
<div style="border: 1px solid gray;padding-left: 5px;">
  #EXTM3U
   <br>
   <% @mp3s.each do |mp3| %>
      <p>
      #EXTINF:<%= mp3.length %>,<%= mp3.artist_name %> - <%= mp3.title %>
      <br>
      <%= mp3.url %>
   <% end %>
</div>
<%= link_to 'Back', mp3s_path %>

app/views/mp3s/show.html.erb
<p id="notice"><%= notice %></p>

<br>

<table border="1">
  <caption>** MP3 Info **</caption>
  <th>
    URL
  </th>
  <th>
    Title
  </th>
  <th>
    Artist Name
  </th>
  <th>
    Length
  </th>
  <th>Average<br>Rating</th>

  <tr>
    <td>
      <%= @mp3.url %>
    </td>
    <td>
      <%= @mp3.title %>
    </td>
    <td>
      <%= @mp3.artist_name %>
    </td>
    <td>
      <%= @mp3.length %>
    </td>
    <td><%= sprintf( "%0.02f", @mp3.average_rating )%></td>
  </tr>
</table>

<br>
<table border="1">
  <caption>** Ratings **</caption>
  <th>
    User
  </th>
  <th>
    Rating
  </th>

  <% @mp3.ratings.each do |rating| %>
    <tr>
      <td>
        <%= rating.user %>
      </td>
      <td>
        <%= rating.value %>
      </td>
    </tr>
  <% end %>
</table>

<br>
<b>Add a rating:</b>
<%= form_for([@mp3, @mp3.ratings.build]) do |f| %>
  <div class="field">
    <%= f.label :user %><br />
    <%= f.text_field :user %>
  </div>
  <div class="field">
    <%= f.label :value %><br />
    <%= f.select :value, (1..5) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>



<%= link_to 'Edit', edit_mp3_path(@mp3) %> |
<%= link_to 'Back', mp3s_path %>

app/views/playlist/_form.html.erb
<% if @mp3s.empty? %>
  <p>
  no songs selected
  <br>
<% else %>
  <div style="border: 1px solid gray;padding-left: 5px;">
    #EXTM3U
     <br>
     <% @mp3s.uniq.each do |mp3| %>
        <p>
        #EXTINF:<%= mp3.length %>,<%= mp3.artist_name %> - <%= mp3.title %>
        <br>
        <%= mp3.url %>
     <% end %>
  </div>

<% end %>

app/views/playlist/create.html.erb
<b>Current Playlist (filtered)</b>

<%= render 'form' %>

<%= link_to 'Back', new_playlist_path %>

app/views/playlist/index.html.erb
<b>Current Playlist (all songs selected)</b>

<%= render 'form' %>

<%= link_to 'Back', new_playlist_path %>

app/views/playlist/new.html.erb
<h1>New Playlist</h1>

<%= form_tag( '/playlist', :method => "put") do %>

  <p>
  Artist Name:
  <%= select("artist", "name", @artists, {:include_blank => false}) %>
  <br>
  Minimum Rating:
  <%= select("rating", "value", @ratings, {:include_blank => false}) %>

  <p>
  <%= submit_tag("Filter Playlist") %>
  <%= link_to 'Select all', playlist_index_path %>
  <%= link_to 'Back to List', mp3s_path %>

<% end %>